version: '3.8'
services: 
    main:
        build: 
            context: .
            dockerfile: Dockerfile
        command: sh -c 'php artisan migrate && php artisan db:seed && php artisan serve --host=0.0.0.0'
        restart: unless-stopped
        volumes:
            - .:/app
        ports:
            - 8000:8000
        depends_on: 
            - db 
    test:
        build: 
            context: .
            dockerfile: Dockerfile
        command: sh -c 'php artisan migrate && php artisan db:seed && php artisan test'
        volumes:
            - .:/app
        depends_on: 
            - db     
    db:
        platform: linux/x86_64
        image: mysql:8.0
        environment: 
            MYSQL_DATABASE: main
            MYSQL_USER: root
            MYSQL_ROOT: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 3306:3306